### ISSUE TITLE
Selective additional files for coding questions

### ISSUE THREAD

**Issue by madooei** [bralax/gecko-action#2]
From README

> This is the default type of question that system interprets. The system looks for any additional files outside of the Question.html to determine the starter code for the question. There must be at least one additional file besides the Question.html file. The language of the starter code will be intepreted from the files extension.

Can it be made to have a top-level JSON config to indicate what other files must be taken as the question? it might be useful to keep additional files (e.g. markdown source of the Question.html, solutions, tests, etc files related to the question) which should not be presented to students.

**Comment by bralax** [comment]
Are saying that in the specific version directory, having the ability to do a "gitignore" type thing (or the reverse) to specify which files should be looked at or not?

**Comment by madooei** [comment]
Well, a conceptual gitignore, or shall it be called `.geckoignore`?

**Comment by bralax** [comment]
@madooei This feature has now been implemented. This tool now supports .geckoignore files as well as Markdown for prompts. To use the new features use v3.0 of the action and you can see the updated documentation in the README.

**Comment by bralax** [comment]
Please note that .geckoignore files function similar to .gitignore files but they can only be placed at the bottom directory as in only in the `{question #}/{version #}/.geckoignore`. The system will also automatically ignore any subdirectory below `{question #}/{version #}/` directory so if you want to save files to not be uploaded, any sub-directory will be ignored
